export const Icon = {
  Feeling: [
    { icon: "😀", name: "happy" },
    { icon: "😇", name: "blessed" },
    { icon: "😘", name: "lovely" },
    { icon: "😍", name: "in love" },
    { icon: "😀", name: "awesome" },
    { icon: "☹️", name: "sad" },
    { icon: "😴", name: "tired" },
    { icon: "😲", name: "surprised" },
    { icon: "😎", name: "cool" },
    { icon: "🤤", name: "hungry" },
    { icon: "😕", name: "bored" },
    { icon: "😢", name: "exhausted" },
    { icon: "😠", name: "angry" },
    { icon: "🤒", name: "sick" },
    { icon: "😴", name: "sleepy" },
    { icon: "🤔", name: "confused" },
    { icon: "😟", name: "worry" },
    { icon: "😱", name: "scared" },
    { icon: "🙂", name: "welcome" },
    { icon: "👿", name: "weird" },
    { icon: "😟", name: "uncomfortable" },
    { icon: "🙂", name: "fine" },
    { icon: "🙄", name: "impatient" },
    { icon: "😨", name: "afraid" },
    { icon: "🤓", name: "smart" },
  ],
  Reaction: [
    { iconURL: "http://localhost:5173/assets/reactions/like.gif", name: "Like", static: "http://localhost:5173/assets/reactions/like_s.png" },
    { iconURL: "http://localhost:5173/assets/reactions/love.gif", name: "Love", static: "http://localhost:5173/assets/reactions/love_s.png" },
    { iconURL: "http://localhost:5173/assets/reactions/haha.gif", name: "Haha", static: "http://localhost:5173/assets/reactions/haha_s.png" },
    { iconURL: "http://localhost:5173/assets/reactions/wow.gif", name: "Wow", static: "http://localhost:5173/assets/reactions/wow_s.png"},
    { iconURL: "http://localhost:5173/assets/reactions/sad.gif", name: "Sad", static: "http://localhost:5173/assets/reactions/sad_s.png" },
    { iconURL: "http://localhost:5173/assets/reactions/angry.gif", name: "Angry", static: "http://localhost:5173/assets/reactions/angry_s.png" },
  ]
}